{
  "text-color": "#f8f8f2",
  "background-color": null,
  "line-number-color": "#5a6577",
  "line-number-background-color": null,
  "text-styles": {
    "Alert": {
      "text-color": "#ff5555",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Annotation": {
      "text-color": "#8a9ad6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Attribute": {
      "text-color": "#8be9fd",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#bd93f9",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#8be9fd",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#f1fa8c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#8a9ad6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#8a9ad6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Constant": {
      "text-color": "#bd93f9",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#ff79c6",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#8be9fd",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#bd93f9",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Documentation": {
      "text-color": "#8a9ad6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Error": {
      "text-color": "#ff5555",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#f1fa8c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#bd93f9",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#50fa7b",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#ff79c6",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Information": {
      "text-color": "#8be9fd",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Keyword": {
      "text-color": "#ff79c6",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Normal": {
      "text-color": "#f8f8f2",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#a8b6d1",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Other": {
      "text-color": "#f8f8f2",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#ff79c6",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "RegionMarker": {
      "text-color": "#8a9ad6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#f1fa8c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#f1fa8c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#f1fa8c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#f8f8f2",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#f1fa8c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Warning": {
      "text-color": "#ffb86c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    }
  }
}
